[network]
layers = [10, 24, 18, 12, 4]
hidden_activation = "leaky_relu"
output_activation = "tanh"

[trainer]
population = 2000

[drone]
mass            = 4.0        # kg
inertia         = 2.383      # kg*m^2
width           = 2.0        # m
height          = 0.175      # m
gravity         = -9.81      # m/s^2, y axis

thruster_offset         = 1.0        # m from center (width / 2)
thruster_rotation_speed = 120.0      # deg/s
thruster_max_angle      = 45         # degrees
thruster_force          = 47.088     # N (g * M * 1.2)
